project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('rugby_team_create/',  include('rugby_team_create.urls')),
    path('admin/', admin.site.urls),
]

rugby_team_create/urls.py
from django.urls import path
from . import views

app_name = 'rugby_team_create'

urlpatterns = [
    path('top/', views.TopTemplate.as_view(), name='top'),
    path('team_list/', views.TeamList.as_view(), name='team_list'),
    path('team_detail/<int:pk>', views.TeamDetail.as_view(), name='team_detail'),
    path('team_create/', views.TeamCreate.as_view(), name='team_create'),
    path('player_list/', views.PlayerList.as_view(), name='player_list'),
    path('player_create/', views.PlayerCreate.as_view(), name='player_create'),
    path('team_delete_confirm/<int:pk>', views.TeamDelete.as_view(), name='team_delete_confirm'),
    path('team_update/<int:pk>', views.TeamUpdate.as_view(), name='team_update')
]

rugby_team_create/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
    name = models.CharField('選手名', max_length=225)
    nationality = models.CharField('代表チーム', max_length=225)

    def __str__(self):
        return self.name


class Team(models.Model):
    name = models.CharField('チーム名', max_length=225)
    creator_name = models.CharField('製作者名', max_length=225, null=True)
    PR1 = models.ForeignKey(Player, verbose_name='左プロップ', on_delete=models.PROTECT, related_name='PR1_player', null=True, blank=True)
    HO = models.ForeignKey(Player, verbose_name='フッカー', on_delete=models.PROTECT, related_name='HO_player', null=True, blank=True)
    PR2 = models.ForeignKey(Player, verbose_name='右プロップ', on_delete=models.PROTECT, related_name='PR2_player', null=True, blank=True)
    LO1 = models.ForeignKey(Player, verbose_name='左ロック', on_delete=models.PROTECT, related_name='LO1_player', null=True, blank=True)
    LO2 = models.ForeignKey(Player, verbose_name='右ロック', on_delete=models.PROTECT, related_name='LO2_player', null=True, blank=True)
    FL1 = models.ForeignKey(Player, verbose_name='左フランカー', on_delete=models.PROTECT, related_name='FL1_player', null=True, blank=True)
    FL2 = models.ForeignKey(Player, verbose_name='右フランカー', on_delete=models.PROTECT, related_name='FL2_player', null=True, blank=True)
    NO8 = models.ForeignKey(Player, verbose_name='ナンバーエイト', on_delete=models.PROTECT, related_name='NO8_player', null=True, blank=True)
    SH = models.ForeignKey(Player, verbose_name='スクラムハーフ', on_delete=models.PROTECT, related_name='SH_player', null=True, blank=True)
    SO = models.ForeignKey(Player, verbose_name='スタンドオフ', on_delete=models.PROTECT, related_name='SO_player', null=True, blank=True)
    WTB1 = models.ForeignKey(Player, verbose_name='左ウイング', on_delete=models.PROTECT, related_name='WTB1_player', null=True, blank=True)
    CTB1 = models.ForeignKey(Player, verbose_name='左センター', on_delete=models.PROTECT, related_name='CTB1_player', null=True, blank=True)
    CTB2 = models.ForeignKey(Player, verbose_name='右センター', on_delete=models.PROTECT, related_name='CTB2_player', null=True, blank=True)
    WTB2 = models.ForeignKey(Player, verbose_name='右ウイング', on_delete=models.PROTECT, related_name='WTB2_player', null=True, blank=True)
    FB = models.ForeignKey(Player, verbose_name='フルバック', on_delete=models.PROTECT, related_name='FB_player', null=True, blank=True)

    def __str__(self):
        return self.name

rugby_team_create/forms.py
from django import forms
from .models import Team, Player

class TeamCreateForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'
        '''widgets = {
            'PR1':forms.Select(attrs={'class': 'PR1_form'}),
            'HO':forms.Select(attrs={'class': 'HO_form'}),
            'PR2':forms.Select(attrs={'class': 'PR2_form'}),
            'LO1':forms.Select(attrs={'class': 'LO1_form'}),
            'LO"':forms.Select(attrs={'class': 'LO2_form'}),
            'FL1':forms.Select(attrs={'class': 'FL1_form'}),
            'FL2':forms.Select(attrs={'class': 'FL2_form'}),
            'NO8':forms.Select(attrs={'class': 'NO8_form'}),
            'SH':forms.Select(attrs={'class': 'SH_form'}),
            'SO':forms.Select(attrs={'class': 'SO_form'}),
            'WTB1':forms.Select(attrs={'class': 'WTB1_form'}),
            'CTB1':forms.Select(attrs={'class': 'CTB1_form'}),
            'CTB2':forms.Select(attrs={'class': 'CTB2_form'}),
            'WTB2':forms.Select(attrs={'class': 'WTB2_form'}),
            'FB':forms.Select(attrs={'class': 'FB_form'}),
        }'''


class PlayerCreateForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = '__all__'

rugby_team_create/views.py
from django.shortcuts import render
from django.views import generic
from .models import Team, Player
from .forms import TeamCreateForm, PlayerCreateForm
from django.urls import reverse_lazy

# Create your views here.
class TopTemplate(generic.TemplateView):
    template_name = 'rugby_team_create/top.html'

class TeamList(generic.ListView):
    model = Team

class TeamDetail(generic.DetailView):
    model = Team

class TeamCreate(generic.CreateView):
    model = Team
    success_url = reverse_lazy('rugby_team_create:team_list')
    form_class = TeamCreateForm


#チームの更新
class TeamUpdate(generic.UpdateView):
    model = Team
    success_url = reverse_lazy('rugby_team_create:team_list')
    form_class = TeamCreateForm  #チーム作成時と同じで良い

#チームの削除
class TeamDelete(generic.DeleteView):
    model = Team
    success_url = reverse_lazy('rugby_team_create:team_list')

#選手一覧表示
class PlayerList(generic.ListView):
    model = Player

#選手登録（入力フォーム、登録後選手一覧ページへ）
class PlayerCreate(generic.CreateView):
    model = Player
    success_url = reverse_lazy('rugby_team_create:player_list')
    form_class = PlayerCreateForm

rugby_team_create/templates/rugby_team_create/base.html
{% load sass_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'rugby_team_create/style.css' %}">
    <link rel="stylesheet" href="{% sass_src 'rugby_team_create/rtc.scss' %}">
  </head>
  <body>
    <header>
      <h1><a href="{% url 'rugby_team_create:top' %}">オリジナルのラグビーチームを作ろう！</a></h1>
      <nav class="nav">
        <ul class="menu">
          <li><a href="{% url 'rugby_team_create:team_create' %}">チーム登録</a></li>
          <li><a href="{% url 'rugby_team_create:team_list' %}">チーム一覧</a></li>
          <li><a href="{% url 'rugby_team_create:player_list' %}">選手一覧</a></li>
          <li><a href="{% url 'rugby_team_create:player_create' %}">選手登録</a></li>
        </ul>
      </nav>
    </header>
    <main>
      {% block main %}{% endblock %}
    </main>
  </body>
</html>

rugby_team_create/templates/rugby_team_create/player_form.html
{% extends 'rugby_team_create/base.html' %}

{% block title %}選手登録{% endblock %}

{% block main %}
    <form action="{% url 'rugby_team_create:player_create' %}" method="POST">
      {{form.as_p}}
      {% csrf_token %}
      <button type="submit">登録</button>
    </form>
{% endblock %}

rugby_team_create/templates/rugby_team_create/player_list.html
{% extends 'rugby_team_create/base.html' %}

{% block title %}選手一覧{% endblock %}

{% block main %}
<table class="player_list_table">
  <tr>
    <th>選手名</th>
    <th>代表国</th>
  </tr>
  {% for player in player_list %}
  <tr>
    <td align="center">{{player.name}}</td>
    <td align="center">{{player.nationality}}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

rugby_team_create/templates/rugby_team_create/team_confirm_delete.html
{% extends 'rugby_team_create/base.html' %}

{% block main %}
    <p>{{ team.name }}を削除しますか？</p>
    <form action="" method="post">
      {% csrf_token %}
      <button type="submit">削除</button>
    </form>
{% endblock %}

rugby_team_create/templates/rugby_team_create/team_detail.html
{% extends 'rugby_team_create/base.html' %}

{% block title %}{{ team.name }}{% endblock %}

{% block main %}

<div class="n_team_detail">
{{team.name}}
<div class="front_row">
  <div class="n_3">
    {{team.PR1}}
  </div>
  <div class="n_4">
    {{team.HO}}
  </div>
  <div class="n_5">
    {{team.PR2}}
  </div>
</div>
<div class="second_row">
  <div class="n_6">
    {{team.LO1}}
  </div>
  <div class="n_7">
    {{team.LO2}}
  </div>
</div>
<div class="back_row_1">
  <div class="n_8">
    {{team.FL1}}
  </div>
  <div class="n_9">
    {{team.FL2}}
  </div>
</div>
<div class="back_row_2">
  <div class="n_10">
   {{team.NO8}}
  </div>
</div>
<div class="SH">
  <div class="n_11">
   {{team.SH}}
  </div>
</div>
<div class="backs_1">
  <div class="n_12">
    {{team.SO}}
  </div>
  <div class="n_13">
    {{team.WTB1}}
  </div>
  <div class="n_14">
    {{team.CTB1}}
  </div>
</div>
<div class="backs_2">
  <div class="n_15">
    {{team.CTB2}}
  </div>
  <div class="n_16">
    {{team.WTB2}}
  </div>
  <div class="n_17">
   {{team.FB}}
  </div>
</div>





</div>
<a href="{% url 'rugby_team_create:team_delete_confirm' team.pk %}">削除</a>
<a href="{% url 'rugby_team_create:team_update' team.pk  %}">更新</a>


{% endblock %}

rugby_team_create/templates/rugby_team_create/team_form.html
{% extends 'rugby_team_create/base.html' %}

{% block title %}チーム作成フォーム{% endblock %}

{% block main %}
<div class="n_form">
<form action="" method="POST">
    {% for field in form %}
        <div class="n_{{forloop.counter}}">
            {{field.label_tag}}
            <div>
            {{field}}
            </div>
        </div>
    {% endfor %}
    <button class="btn1" type="submit">登録</button>
    {% csrf_token %}
</form>
</div>

{% endblock %}

rugby_team_create/templates/rugby_team_create/team_list.html
{% extends 'rugby_team_create/base.html' %}

{% block title %}チーム一覧{% endblock %}

{% block main %}
<table>
  <tr>
    <th>チーム名</th>
    <th>製作者</th>
  </tr>
{% for team in team_list %}
 <tr>
   <td align="center"><a href="{% url 'rugby_team_create:team_detail' team.id %}">{{team.name}}</a></td>
   <td align="center">{{team.creator_name}}</td>
 </tr>
{% endfor %}
</table>
{% endblock %}

rugby_team_create/templates/rugby_team_create/top.html
{% extends 'rugby_team_create/base.html' %}
{% load static %}

{% block title %}トップページ{% endblock %}

{% block main %}
<div class="top_image">
  <img src="{% static 'rugby_team_create/top_image.jpg' %}" alt="オリジナルのラグビーチームを作ろう！">
</div>
{% endblock %}